### ISSUE TITLE
ssh_config from jenkins is failing

### ISSUE THREAD

**Issue by hkumarmk** [JioCloud/puppet-rjil#319]
python -m jiocloud.orchestrate ssh_config is failing from jenkins workspace (/var/lib/jenkins/workspace/puppet-rjil-gate) and throwing below error.

+ python -m jiocloud.apply_resources ssh_config --project_tag=testjenkins-puppet-rjil-gate-509 --mappings=environment/hp.map.yaml environment/full.yaml
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/lib/jenkins/workspace/puppet-rjil-gate/venv/src/jiocloud/jiocloud/apply_resources.py", line 218, in <module>
    servers = apply_resources.generate_desired_servers(resources, args.project_tag)
  File "/var/lib/jenkins/workspace/puppet-rjil-gate/venv/src/jiocloud/jiocloud/apply_resources.py", line 69, in generate_desired_servers
    server[k_] = mappings.get(k_, {}).get(v_, v_)
AttributeError: 'str' object has no attribute 'get'

**Comment by hkumarmk** [comment]
I see jenkins workspace has old python-jiocloud module in its venv and because of which it is erroring out.

>>> dir(jiocloud.orchestrate)
['DeploymentOrchestrator', 'DiscoveryClient', 'HTTPError', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'argparse', 'errno', 'etcd', 'json', 'main', 'netifaces', 'os', 're', 'socket', 'sys', 'time', 'urllib3', 'urlparse', 'yaml']
