### ISSUE TITLE
issues with scaling contrail

### ISSUE THREAD

**Issue by bodepd** [JioCloud/puppet-rjil#428]
I am seeing several issues with scaling contrail that I am having trouble explaining. This ticket isn't really actionable, For the moment I'm just starting to catalog things as I run into them. I feel that I can at least partially resolve these issues with stricter deps between contrail and it's clustered data services, although using dependencies as the fix does not seem like really dealing with the underlying causes.

* one machine has been stuck running puppet with the following call which has been running for more than 1 hour without timing out.

````
/usr/bin/python /usr/sbin/contrail-provision-control --admin_user admin --admin_password Chang3M3 --api_server_ip 127.0.0.1 --api_server_port 8082 --host_name ct2-testjenkins-puppet-rjil-gate-707 --host_ip 10.0.0.230 --router_asn 64512 --admin_tenant_name openstack --oper add
````

We may need to add our own timeouts to the above operation to ensure that it will exit and fail if it gets stuck, we should also open a ticket to see if we can track down the issue and fix it upstream

* Often, the api service is in a stuck state, where the service us running, but it is not bound to a port:

I can see logs that indicate a failure to connect to cassandra in this case, but I can manually make a connection to the same address

* sometimes the schema service is not bound to a port ( I don't currently have a recreate on this, but  l will post more information when I do)

**Comment by bodepd** [comment]
I also ran into the following (which I had seen before and though I resolved by setting just a single seed node for cassandra)

````
The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/bin/contrail-api", line 9, in <module>
    load_entry_point('vnc-cfg-api-server==0.1dev', 'console_scripts', 'contrail-api')()
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py", line 1572, in server_main
    main()
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py", line 1531, in main
    vnc_api_server = VncApiServer(args_str)
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py", line 422, in __init__
    self._db_init_entries()
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py", line 1074, in _db_init_entries
    config_version=CONFIG_VERSION))
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py", line 1125, in _create_singleton_entry
    self._db_conn.dbe_create(obj_type, obj_ids, obj_dict)
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_ifmap.py", line 1701, in wrapper2
    ret = func(self, obj_type, obj_ids, obj_dict)
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_ifmap.py", line 1719, in dbe_create
    (ok, result) = method(obj_ids, obj_dict)
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/gen/vnc_cassandra_client_gen.py", line 3885, in _cassandra_global_system_config_create
    self._create_prop(bch, obj_ids['uuid'], 'autonomous_system', field)
TypeError: string indices must be integers, not str
````

I believe the issue is related to initialization data in cassandra getting dropped when the cluster is formed.

**Comment by bodepd** [comment]
a more detailed stack trace of the message above:

````
FO:api-0:Connected to ZooKeeper!
INFO:api-0:Sending request(xid=1): Create(path=u'/fq-name-to-uuid/global_system_config:default-global-system-config', data='7e6573c7-8d98-490f-8930-618d3c1b7ff5', acl=[ACL(perms=31, acl_list=['ALL'], id=Id(scheme='world', id='anyone'))], flags=0)
INFO:api-0:Received error(xid=1) NodeExistsError((), {})
INFO:api-0:Sending request(xid=2): GetData(path=u'/fq-name-to-uuid/global_system_config:default-global-system-config', watcher=None)
INFO:api-0:Received error(xid=2) NoNodeError((), {})
<type 'exceptions.TypeError'>
Python 2.7.6: /usr/bin/python
Thu Feb 19 12:26:34 2015

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/bin/contrail-api in <module>()
    6
    7 if __name__ == '__main__':
    8     sys.exit(
    9         load_entry_point('vnc-cfg-api-server==0.1dev', 'console_scripts', 'contrail-api')()
   10     )
load_entry_point = <function load_entry_point>

 /usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py in server_main(args_str=None)
 1570     cgitb.enable(format='text')
 1571
 1572     main()
 1573 #server_main
 1574
global main = <function main>

 /usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py in main(args_str=None)
 1529 server = None
 1530 def main(args_str=None):
 1531     vnc_api_server = VncApiServer(args_str)
 1532     # set module var for uses with import e.g unit test
 1533     global server
vnc_api_server undefined
global VncApiServer = <class 'vnc_cfg_api_server.vnc_cfg_api_server.VncApiServer'>
args_str = None

 /usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py in __init__(self=<vnc_cfg_api_server.vnc_cfg_api_server.VncApiServer object>, args_str='--conf_file /etc/contrail/contrail-api.conf')
  420         else:
  421             self._db_connect(self._args.reset_config)
  422             self._db_init_entries()
  423
  424         # Cpuinfo interface
self = <vnc_cfg_api_server.vnc_cfg_api_server.VncApiServer object>
self._db_init_entries = <bound method VncApiServer._db_init_entries of <...i_server.vnc_cfg_api_server.VncApiServer object>>

 /usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py in _db_init_entries(self=<vnc_cfg_api_server.vnc_cfg_api_server.VncApiServer object>)
 1072         glb_sys_cfg = self._create_singleton_entry(
 1073             GlobalSystemConfig(autonomous_system=64512,
 1074                                config_version=CONFIG_VERSION))
 1075         def_domain = self._create_singleton_entry(Domain())
 1076         ip_fab_vn = self._create_singleton_entry(
config_version undefined
global CONFIG_VERSION = '1.0'

 /usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py in _create_singleton_entry(self=<vnc_cfg_api_server.vnc_cfg_api_server.VncApiServer object>, singleton_obj=<vnc_cfg_api_server.gen.resource_common.GlobalSystemConfig object>)
 1123             (ok, result) = self._db_conn.dbe_alloc(obj_type, obj_dict)
 1124             obj_ids = result
 1125             self._db_conn.dbe_create(obj_type, obj_ids, obj_dict)
 1126             method = '_%s_create_default_children' % (method_name)
 1127             def_children_method = getattr(self, method)
self = <vnc_cfg_api_server.vnc_cfg_api_server.VncApiServer object>
self._db_conn = <vnc_cfg_api_server.vnc_cfg_ifmap.VncDbClient object>
self._db_conn.dbe_create = <bound method VncDbClient.wrapper2 of <vnc_cfg_api_server.vnc_cfg_ifmap.VncDbClient object>>
obj_type = 'global-system-config'
obj_ids = 'FQ Name: /fq-name-to-uuid/global_system_config:d...global-system-config exists already with ID: None'
obj_dict = {'autonomous_system': 64512, 'config_version': '1.0', 'fq_name': [u'default-global-system-config'], 'id_perms': {u'created': 0, u'description': None, u'enable': True, u'last_modified': 0, u'permissions': {u'group': u'cloud-admin-group', u'group_access': 7, u'other_access': 7, u'owner': u'cloud-admin', u'owner_access': 7}, u'user_visible': True, u'uuid': None}, 'uuid': None}

 /usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_ifmap.py in wrapper2(self=<vnc_cfg_api_server.vnc_cfg_ifmap.VncDbClient object>, obj_type='global-system-config', obj_ids='FQ Name: /fq-name-to-uuid/global_system_config:d...global-system-config exists already with ID: None', obj_dict={'autonomous_system': 64512, 'config_version': '1.0', 'fq_name': [u'default-global-system-config'], 'id_perms': {u'created': 0, u'description': None, u'enable': True, u'last_modified': 0, u'permissions': {u'group': u'cloud-admin-group', u'group_access': 7, u'other_access': 7, u'owner': u'cloud-admin', u'owner_access': 7}, u'user_visible': True, u'uuid': None}, 'uuid': None})
 1699                                                         obj_ids, obj_dict)
 1700                 try:
 1701                     ret = func(self, obj_type, obj_ids, obj_dict)
 1702                     trace_msg(trace, 'DBRequestTraceBuf',
 1703                               self._sandesh)
ret undefined
func = <function dbe_create>
self = <vnc_cfg_api_server.vnc_cfg_ifmap.VncDbClient object>
obj_type = 'global-system-config'
obj_ids = 'FQ Name: /fq-name-to-uuid/global_system_config:d...global-system-config exists already with ID: None'
obj_dict = {'autonomous_system': 64512, 'config_version': '1.0', 'fq_name': [u'default-global-system-config'], 'id_perms': {u'created': 0, u'description': None, u'enable': True, u'last_modified': 0, u'permissions': {u'group': u'cloud-admin-group', u'group_access': 7, u'other_access': 7, u'owner': u'cloud-admin', u'owner_access': 7}, u'user_visible': True, u'uuid': None}, 'uuid': None}

 /usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_ifmap.py in dbe_create(self=<vnc_cfg_api_server.vnc_cfg_ifmap.VncDbClient object>, obj_type='global-system-config', obj_ids='FQ Name: /fq-name-to-uuid/global_system_config:d...global-system-config exists already with ID: None', obj_dict={'autonomous_system': 64512, 'config_version': '1.0', 'fq_name': [u'default-global-system-config'], 'id_perms': {u'created': 0, u'description': None, u'enable': True, u'last_modified': 0, u'permissions': {u'group': u'cloud-admin-group', u'group_access': 7, u'other_access': 7, u'owner': u'cloud-admin', u'owner_access': 7}, u'user_visible': True, u'uuid': None}, 'uuid': None})
 1717         method = getattr(
 1718             self._cassandra_db, "_cassandra_%s_create" % (method_name))
 1719         (ok, result) = method(obj_ids, obj_dict)
 1720
 1721         # publish to ifmap via msgbus
ok undefined
result undefined
method = <bound method VncCassandraClient._cassandra_glob..._server.vnc_cfg_ifmap.VncCassandraClient object>>
obj_ids = 'FQ Name: /fq-name-to-uuid/global_system_config:d...global-system-config exists already with ID: None'
obj_dict = {'autonomous_system': 64512, 'config_version': '1.0', 'fq_name': [u'default-global-system-config'], 'id_perms': {u'created': 0, u'description': None, u'enable': True, u'last_modified': 0, u'permissions': {u'group': u'cloud-admin-group', u'group_access': 7, u'other_access': 7, u'owner': u'cloud-admin', u'owner_access': 7}, u'user_visible': True, u'uuid': None}, 'uuid': None}

 /usr/lib/python2.7/dist-packages/vnc_cfg_api_server/gen/vnc_cassandra_client_gen.py in _cassandra_global_system_config_create(self=<vnc_cfg_api_server.vnc_cfg_ifmap.VncCassandraClient object>, obj_ids='FQ Name: /fq-name-to-uuid/global_system_config:d...global-system-config exists already with ID: None', obj_dict={'autonomous_system': 64512, 'config_version': '1.0', 'fq_name': [u'default-global-system-config'], 'id_perms': {u'created': 0, u'description': None, u'enable': True, u'last_modified': 0, u'permissions': {u'group': u'cloud-admin-group', u'group_access': 7, u'other_access': 7, u'owner': u'cloud-admin', u'owner_access': 7}, u'user_visible': True, u'uuid': None}, 'uuid': None})
 3883         field = obj_dict.get('autonomous_system', None)
 3884         if field is not None:
 3885             self._create_prop(bch, obj_ids['uuid'], 'autonomous_system', field)
 3886
 3887         field = obj_dict.get('config_version', None)
self = <vnc_cfg_api_server.vnc_cfg_ifmap.VncCassandraClient object>
self._create_prop = <bound method VncCassandraClient._create_prop of..._server.vnc_cfg_ifmap.VncCassandraClient object>>
bch = <pycassa.batch.CfMutator object>
obj_ids = 'FQ Name: /fq-name-to-uuid/global_system_config:d...global-system-config exists already with ID: None'
field = 64512
<type 'exceptions.TypeError'>: string indices must be integers, not str
    __class__ = <type 'exceptions.TypeError'>
    __delattr__ = <method-wrapper '__delattr__' of exceptions.TypeError object>
    __dict__ = {}
    __doc__ = 'Inappropriate argument type.'
    __format__ = <built-in method __format__ of exceptions.TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of exceptions.TypeError object>
    __getitem__ = <method-wrapper '__getitem__' of exceptions.TypeError object>
    __getslice__ = <method-wrapper '__getslice__' of exceptions.TypeError object>
    __hash__ = <method-wrapper '__hash__' of exceptions.TypeError object>
    __init__ = <method-wrapper '__init__' of exceptions.TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of exceptions.TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of exceptions.TypeError object>
    __repr__ = <method-wrapper '__repr__' of exceptions.TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of exceptions.TypeError object>
    __setstate__ = <built-in method __setstate__ of exceptions.TypeError object>
    __sizeof__ = <built-in method __sizeof__ of exceptions.TypeError object>
    __str__ = <method-wrapper '__str__' of exceptions.TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __unicode__ = <built-in method __unicode__ of exceptions.TypeError object>
    args = ('string indices must be integers, not str',)
    message = 'string indices must be integers, not str'

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/bin/contrail-api", line 9, in <module>
    load_entry_point('vnc-cfg-api-server==0.1dev', 'console_scripts', 'contrail-api')()
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py", line 1572, in server_main
    main()
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py", line 1531, in main
    vnc_api_server = VncApiServer(args_str)
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py", line 422, in __init__
    self._db_init_entries()
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py", line 1074, in _db_init_entries
    config_version=CONFIG_VERSION))
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_api_server.py", line 1125, in _create_singleton_entry
    self._db_conn.dbe_create(obj_type, obj_ids, obj_dict)
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_ifmap.py", line 1701, in wrapper2
    ret = func(self, obj_type, obj_ids, obj_dict)
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/vnc_cfg_ifmap.py", line 1719, in dbe_create
    (ok, result) = method(obj_ids, obj_dict)
  File "/usr/lib/python2.7/dist-packages/vnc_cfg_api_server/gen/vnc_cassandra_client_gen.py", line 3885, in _cassandra_global_system_config_create
    self._create_prop(bch, obj_ids['uuid'], 'autonomous_system', field)
TypeError: string indices must be integers, not str
````

When contrail enters this state, I am not entirely sure if it is recoverable, or how to recover

**Comment by bodepd** [comment]
sometimes the contrail-schema nodes get into a stuck state where no one will take the leadership role. I have a feeling that it may be b/c of ntp, but I need to isolate with a debugger.

**Comment by bodepd** [comment]
I just saw a case where one of the contrail-api services was was dead, but still thought the service was running and the port bound, I got this node out of it's stuck state by restarting

**Comment by bodepd** [comment]
the last error message that I saw when it was in this stuck state was the following:

````
INFO:pycassa.pool:Connection 140411342253392 (10.0.0.17:9160) in pool 140411342253072 failed: timed out
````
