### ISSUE TITLE
rpc timeout issues on various openstack components 

### ISSUE THREAD

**Issue by hkumarmk** [JioCloud/puppet-rjil#517]
I am not sure if this is deadly or just kind of errors, but sometimes we see missing messages and other problems and we see these messages that time also.

We (Soren and me) did some detailed investigation previously, but in the middle of the investigation, the issue jst fixed automatically (within few mins ).

HEre is the error we see on other component's logs also

2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     instance_id, address)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/metadata/base.py", line 509, in get_metadata_by_instance_id
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     return InstanceMetadata(instance, address)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/metadata/base.py", line 148, in __init__
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     obj_base.obj_to_primitive(instance))
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/conductor/api.py", line 274, in get_ec2_ids
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     return self._manager.get_ec2_ids(context, instance)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/conductor/rpcapi.py", line 413, in get_ec2_ids
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     instance=instance_p)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/rpc/client.py", line 150, in call
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     wait_for_reply=True, timeout=timeout)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/transport.py", line 90, in _send
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     timeout=timeout)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_zmq.py", line 927, in send
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     return self._send(target, ctxt, message, wait_for_reply, timeout)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_zmq.py", line 921, in _send
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     allowed_remote_exmods=self._allowed_remote_exmods)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_zmq.py", line 756, in _multi_send
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     envelope, allowed_remote_exmods)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_zmq.py", line 691, in _call
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     msg = msg_waiter.recv()
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_zmq.py", line 212, in recv
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     return self.sock.recv_multipart(**kwargs)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/eventlet/green/zmq.py", line 345, in recv_multipart
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     return _Socket_recv_multipart(self, flags, copy, track)
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 265, in recv_multipart
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     parts = [self.recv(flags, copy=copy, track=track)]
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/eventlet/green/zmq.py", line 324, in recv
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     self._eventlet_recv_event.block()
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/eventlet/green/zmq.py", line 97, in block
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     self._hub.switch()
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 187, in switch
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler     return self.greenlet.switch()
2015-04-03 12:12:21.327 17876 TRACE nova.api.metadata.handler Timeout: Timeout while waiting on RPC response - topic: "<unknown>", RPC method: "<unknown>" info: "<unknown>"

**Comment by hkumarmk** [comment]
I see this error in the vm status also

$ nova show 57fc6bc5-896f-4839-ad16-1148a3cfbb46
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Property                             | Value                                                                                                                                                                      |
+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                                                                                                                                                     |
| OS-EXT-AZ:availability_zone          | nova                                                                                                                                                                       |
| OS-EXT-STS:power_state               | 0                                                                                                                                                                          |
| OS-EXT-STS:task_state                | -                                                                                                                                                                          |
| OS-EXT-STS:vm_state                  | deleted                                                                                                                                                                    |
| OS-SRV-USG:launched_at               | -                                                                                                                                                                          |
| OS-SRV-USG:terminated_at             | 2015-04-03T12:18:01.000000                                                                                                                                                 |
| accessIPv4                           |                                                                                                                                                                            |
| accessIPv6                           |                                                                                                                                                                            |
| config_drive                         |                                                                                                                                                                            |
| created                              | 2015-04-03T12:05:41Z                                                                                                                                                       |
| fault                                | {"message": "Timeout while waiting on RPC response - topic: \"<unknown>\", RPC method: \"<unknown>\" info: \"<unknown>\"", "code": 500, "created": "2015-04-03T12:07:45Z"} |
| flavor                               | small (da9ba7b5-be67-4a62-bb35-a362e05ba2f2)                                                                                                                               |
| hostId                               | 1fa729e6682b34cfc20b403d71c33b6b28fb831c1dbc5ff57e9c6a8e                                                                                                                   |
| id                                   | 57fc6bc5-896f-4839-ad16-1148a3cfbb46                                                                                                                                       |
| image                                | Attempt to boot from volume - no image supplied                                                                                                                            |
| key_name                             | combo                                                                                                                                                                      |
| metadata                             | {}                                                                                                                                                                         |
| name                                 | new1                                                                                                                                                                       |
| os-extended-volumes:volumes_attached | [{"id": "bd208799-4bcc-4722-aaa2-c425e9c92da0"}]                                                                                                                           |
| status                               | DELETED                                                                                                                                                                    |
| tenant_id                            | 103fabdd5c5b4b088512b21a577e5986                                                                                                                                           |
| updated                              | 2015-04-03T12:18:01Z                                                                                                                                                       |
| user_id                              | 6e41255dba7f499f9028f26834779eba                                                                                                                                           |

**Comment by hkumarmk** [comment]
on further debuging, I see nova metadata is throwing the error while trying to get instance metadata for some specific vms - most of vms booted on jenkins. I checked to see any correlation with the hypervisor nodes, but I dont see any. Here is the results of my investiation

We have dhcp lease expired issues today morning on cp nodes (refer #515 for more information) which I had to manually fix by logging into server console and restart the network. That may be causing this issue. We would need engineering see what is happening there (I hope stack trace and logs help to shed some light on it).

### This is the all instances causing issues
s=`grep "Failed to get metadata for instance id" nova-api.log |  awk '{print $NF}' | sort -u` ## Done this on both oc1 and ocdb1, both given same set of instances
hkumar@ocdb1-production:~$ for i in $s; do echo -n "$i: "; nova show $i | grep " name\|hypervisor_hostname" | awk '{printf $4", "}'; echo ; done
dd4834fe-3964-4b80-a777-3ec7ba854a97: cp8-production.novalocal, stmonleader1_testjenkins-puppet-rjil-gate-998, 
09107539-2d60-43a7-b9cd-2a216e7abec4: cp3-production.novalocal, stmon1_testjenkins-puppet-rjil-gate-1010, 
0c5f829b-86c4-4bc3-b375-3cb5afc4a847: cp26-production.novalocal, gcp1_test2226, 
15c8520a-4d86-4c5e-b6c5-40f435f727b8: cp29-production.novalocal, haproxy1_test2226, 
1ad1e385-e52d-4494-9745-8601920b25be: cp11-production.novalocal, cp1_testjenkins-puppet-rjil-gate-1010, 
1ffab411-e306-4d85-af9b-ab24ea174ab4: cp12-production.novalocal, stmonleader1_testjenkins-puppet-rjil-gate-1010, 
2039a04d-f458-42f6-be8e-c61df71d3042: cp7-production.novalocal, gcp1_testjenkins-puppet-rjil-gate-998, 
253b15ad-fc69-4a9c-9a39-e03c2f5dd0ab: cp9-production.novalocal, stmon2_test2226, 
2ccf10cf-6739-494e-b7eb-cb98a54b3cc4: cp21-production.novalocal, oc1_testjenkins-puppet-rjil-gate-1011, 
3338346e-0ba7-4b89-931d-7d0677f259ae: cp5-production.novalocal, stmon1_testjenkins-puppet-rjil-gate-1011, 
3643e0cf-aad1-483b-8702-dc58a311894e: cp6-production.novalocal, haproxy1_testjenkins-puppet-rjil-gate-998, 
3e8ddcdc-4fed-4962-b008-ff141446440b: cp30-production.novalocal, oc1_test2226, 
46ee6734-25e1-48d5-ae0a-e42694839bfd: cp2-production.novalocal, ct1_testjenkins-puppet-rjil-gate-998, 
48c9dfaf-7778-4145-ab92-566b6eabe9b1: cp13-production.novalocal, st1_testjenkins-puppet-rjil-gate-1010, 
4a5819c2-2388-4c9d-a1dd-bbc9c3895bc1: cp13-production.novalocal, ocdb1_testjenkins-puppet-rjil-gate-1010, 
5092f244-b733-4793-b59f-bd840cbce2a6: cp23-production.novalocal, ocdb1_testjenkins-puppet-rjil-gate-1011, 
56065793-128b-4049-a145-38976f08e7c3: cp17-production.novalocal, cp2_testjenkins-puppet-rjil-gate-1011, 
60a3a9f3-21be-4fdd-8780-c477f4ac715a: cp16-production.novalocal, gcp1_testjenkins-puppet-rjil-gate-1011, 
6ffed1f6-f6f4-42ec-a660-67e974c4f726: cp24-production.novalocal, st1_testjenkins-puppet-rjil-gate-1011, 
7063a803-7d15-4737-bc9e-7c7501fd9c7f: cp10-production.novalocal, gcp1_testjenkins-puppet-rjil-gate-1010, 
7172a1ea-2f88-412f-a7e8-0832c0763114: cp21-production.novalocal, cp1_test2226, 
74e0c472-d556-4cf4-af4c-ea2458e7ea19: cp13-production.novalocal, cp2_testjenkins-puppet-rjil-gate-1010, 
7e1d2f70-6fad-48e9-82a4-c48381e8cefe: cp19-production.novalocal, haproxy1_testjenkins-puppet-rjil-gate-1011, 
7ea55704-b01e-4136-952e-9bc2a8b7c0e4: cp25-production.novalocal, cp1_testjenkins-puppet-rjil-gate-1011, 
866b7d71-3b12-4e07-a803-7a017ccaf718: cp18-production.novalocal, stmonleader1_testjenkins-puppet-rjil-gate-1011, 
895d5399-4e3f-4969-9c01-471369d6df89: cp4-production.novalocal, stmon1_testjenkins-puppet-rjil-gate-998, 
90bf763e-88df-46fb-b332-fac89afcb396: cp15-production.novalocal, cp2_test2226, 
99a2b672-7d29-47b9-bfbf-29a057109c49: cp12-production.novalocal, haproxy1_testjenkins-puppet-rjil-gate-1010, 
a57519eb-2751-472d-bd11-ad78a849b822: cp29-production.novalocal, stmon1_test2226, 
adfd479c-939a-4c11-a774-4551c16add4d: cp9-production.novalocal, oc1_testjenkins-puppet-rjil-gate-998, 
b0b499ad-15de-4d0b-86fb-c22c0cadc490: cp15-production.novalocal, ocdb1_test2226, 
b7a16a3f-af4c-4135-b97c-ad1982480472: cp12-production.novalocal, stmon2_testjenkins-puppet-rjil-gate-1010, 
b82c63de-2199-482e-8af0-10addf46f239: cp27-production.novalocal, stmonleader1_test2226, 
bc1bf3d7-aa81-4a69-b8ab-03a72178b1ec: gcp1-production.novalocal, stmon2_testjenkins-puppet-rjil-gate-998, 
c9787eb2-661b-41a5-b523-f61044a56c26: cp10-production.novalocal, ct1_testjenkins-puppet-rjil-gate-1010, 
d00deb92-5cf4-46f7-b636-683960ae88ee: cp22-production.novalocal, stmon2_testjenkins-puppet-rjil-gate-1011, 
d1133e66-0cbd-4bb6-8c32-e0e787af5e8e: cp6-production.novalocal, ocdb1_testjenkins-puppet-rjil-gate-998, 
d79db7fd-19fd-4e4c-960c-f6079b8daf4c: cp10-production.novalocal, cp2_testjenkins-puppet-rjil-gate-998, 
d8d715c9-a7d2-46ca-af27-8e1f070627b5: cp11-production.novalocal, cp1_testjenkins-puppet-rjil-gate-998, 
e38bf740-1e75-4c15-98c8-92878981cdd9: cp19-production.novalocal, ct1_testjenkins-puppet-rjil-gate-1011, 

### here is the test projects under which the vms got problems

test2226
testjenkins-puppet-rjil-gate-1010
testjenkins-puppet-rjil-gate-1011
testjenkins-puppet-rjil-gate-998

### It started today morning UTC (~ 3 PM IST)
$ grep -B50 "Timeout: Timeout while waiting on RPC response" nova-api.log  | grep "ERROR\|Timeout: Timeout" | grep -B1 Timeout | head -2
2015-04-03 10:34:39.905 17740 ERROR nova.api.metadata.handler [req-37e84f59-b592-4a42-9272-c5f8e64cd7cc None None] Failed to get metadata for instance id: 99a2b672-7d29-47b9-bfbf-29a057109c49
2015-04-03 10:34:39.905 17740 TRACE nova.api.metadata.handler Timeout: Timeout while waiting on RPC response - topic: "<unknown>", RPC method: "<unknown>" info: "<unknown>"

### As soon as I deleted above vms, the issues went away, here is the last set of errors
$ grep  "Timeout: Timeout while waiting on RPC response" nova-api.log| tail -2
2015-04-03 14:05:29.684 25133 TRACE nova.api.metadata.handler Timeout: Timeout while waiting on RPC response - topic: "<unknown>", RPC method: "<unknown>" info: "<unknown>"
2015-04-03 14:05:30.085 25132 TRACE nova.api.metadata.handler Timeout: Timeout while waiting on RPC response - topic: "<unknown>", RPC method: "<unknown>" info: "<unknown>"

### Complete stack trace
2f923] 10.140.192.30,127.0.0.1 "GET /v2/d8de26e6d4d8463087bd54c57df2f923/servers/99a2b672-7d29-47b9-bfbf-29a057109c49 HTTP/1.1" status: 200 len: 1859 time: 0.2889621
2015-04-03 13:15:41.259 33196 ERROR nova.api.metadata.handler [req-6d71f80c-fcb9-4202-909b-31b394078ba1 None None] Failed to get metadata for instance id: 15c8520a-4d86
-4c5e-b6c5-40f435f727b8
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler Traceback (most recent call last):
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/metadata/handler.py", line 189, in _handle_instance_id_r
equest
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     remote_address)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/metadata/handler.py", line 91, in get_metadata_by_instan
ce_id
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     instance_id, address)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/metadata/base.py", line 509, in get_metadata_by_instance_id
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     return InstanceMetadata(instance, address)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/metadata/base.py", line 135, in __init__
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     instance['host'], capi)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/ec2/ec2utils.py", line 174, in get_availability_zone_by_host
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler Traceback (most recent call last):
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/metadata/handler.py", line 189, in _handle_instance_id_r
equest
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     remote_address)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/metadata/handler.py", line 91, in get_metadata_by_instan
ce_id
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     instance_id, address)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/metadata/base.py", line 509, in get_metadata_by_instance_id
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     return InstanceMetadata(instance, address)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/metadata/base.py", line 135, in __init__
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     instance['host'], capi)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/api/ec2/ec2utils.py", line 174, in get_availability_zone_by_host
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     context.get_admin_context(), host, conductor_api)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/availability_zones.py", line 86, in get_host_availability_zone
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     context, host, key='availability_zone')
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/conductor/api.py", line 120, in aggregate_metadata_get_by_host
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     key)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/nova/conductor/rpcapi.py", line 195, in aggregate_metadata_get_by_host
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     key=key)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/rpc/client.py", line 150, in call
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     wait_for_reply=True, timeout=timeout)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/transport.py", line 90, in _send
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     timeout=timeout)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_zmq.py", line 927, in send
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     return self._send(target, ctxt, message, wait_for_reply, timeout)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_zmq.py", line 921, in _send
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     allowed_remote_exmods=self._allowed_remote_exmods)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_zmq.py", line 756, in _multi_send
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     envelope, allowed_remote_exmods)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_zmq.py", line 691, in _call
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     msg = msg_waiter.recv()
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_zmq.py", line 212, in recv
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     return self.sock.recv_multipart(**kwargs)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/eventlet/green/zmq.py", line 345, in recv_multipart
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     return _Socket_recv_multipart(self, flags, copy, track)
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 265, in recv_multipart
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     parts = [self.recv(flags, copy=copy, track=track)]
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/eventlet/green/zmq.py", line 324, in recv
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     self._eventlet_recv_event.block()
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/eventlet/green/zmq.py", line 97, in block
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     self._hub.switch()
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler   File "/usr/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 187, in switch
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler     return self.greenlet.switch()
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler Timeout: Timeout while waiting on RPC response - topic: "<unknown>", RPC method: "<unknown>" info: "<unknown>"
2015-04-03 13:15:41.259 33196 TRACE nova.api.metadata.handler 
2015-04-03 13:15:41.263 33196 INFO nova.api.ec2 [-] 60.46683s 10.140.192.30 GET /latest/user-data/ None:None 500 [Ruby] text/plain text/html
2015-04-03 13:15:41.264 33196 INFO nova.metadata.wsgi.server [-] 10.0.0.4,10.140.192.30 "GET /latest/user-data/ HTTP/1.1" status: 500 len: 343 time: 60.0480149

**Comment by hkumarmk** [comment]
Oh yeah, I tried to reduce the threads for nova compute, metadata, ec2, conductor from 32 each to 4 each to see if large number of threads accessing the rpc is causing this issue, but it did not fix it.
